apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: operators
  namespace: openshift-gitops
spec:
  generators:
  - git:
      repoURL: https://github.com/euanhume/openshift-cluster-config-three
      revision: HEAD
      directories:
      - path: operators/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: operators
      source:
        repoURL: https://github.com/euanhume/openshift-cluster-config-three
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'  # or use a naming convention
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true